git_error: instead of giterr
libgit2 has updated some function signatures for consistency,
including the `giterr` family of functions which is now `git_error`.